"""add bullet_embeddings table

Revision ID: 0edc54022e3a
Revises: 33b93f72cf62
Create Date: 2026-07-05 15:13:24.515423

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edc54022e3a'
down_revision: Union[str, Sequence[str], None] = '33b93f72cf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bullet_embeddings',
    sa.Column('resume_version_id', sa.Uuid(), nullable=False),
    sa.Column('bullet_ref', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_bullet_embeddings_resume_version_id_resume_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bullet_embeddings')),
    sa.UniqueConstraint('resume_version_id', 'bullet_ref', name=op.f('uq_bullet_embeddings_resume_version_id_bullet_ref'))
    )
    op.create_index('ix_bullet_embeddings_embedding', 'bullet_embeddings', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_bullet_embeddings_resume_version_id'), 'bullet_embeddings', ['resume_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bullet_embeddings_resume_version_id'), table_name='bullet_embeddings')
    op.drop_index('ix_bullet_embeddings_embedding', table_name='bullet_embeddings', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('bullet_embeddings')
    # ### end Alembic commands ###
